# Copia como 20-secret-db.yaml y cambia la contraseña antes de aplicar.
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-db-secret
  namespace: bookstore
type: Opaque
stringData:
  DB_HOST: mysql-bookstore-primary.bookstore.svc.cluster.local
  DB_USER: bookstore_admin
  DB_PASSWORD: CAMBIA_ESTA_PASSWORD
  DB_NAME: bookstore_db
