apiVersion: v1
kind: Service
metadata:
  name: mysql-bookstore-primary
  namespace: bookstore
  labels: { app: mysql-bookstore, role: primary }
spec:
  selector: { app: mysql-bookstore, role: primary }
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-bookstore-primary
  namespace: bookstore
  labels: { app: mysql-bookstore, role: primary }
spec:
  serviceName: mysql-bookstore-primary
  replicas: 1
  selector:
    matchLabels: { app: mysql-bookstore, role: primary }
  template:
    metadata:
      labels: { app: mysql-bookstore, role: primary }
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: bookstore-db-secret, key: DB_PASSWORD } }
            - name: MYSQL_DATABASE
              valueFrom: { secretKeyRef: { name: bookstore-db-secret, key: DB_NAME } }
            - name: MYSQL_USER
              valueFrom: { secretKeyRef: { name: bookstore-db-secret, key: DB_USER } }
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: bookstore-db-secret, key: DB_PASSWORD } }
          args:
            - "--server-id=1"
            - "--log-bin=mysql-bin"
            - "--binlog_format=ROW"
            - "--gtid_mode=ON"
            - "--enforce-gtid-consistency=ON"
            - "--log-replica-updates=ON"
            - "--binlog_expire_logs_seconds=86400"
          readinessProbe:
            exec:
              command: ["bash","-lc","mysqladmin ping -h 127.0.0.1 -p\"$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["bash","-lc","mysqladmin ping -h 127.0.0.1 -p\"$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 40
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          emptyDir: {}  # Lab sin EBS; en prod: PVC por pod
